name: Test

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js v14
      uses: actions/setup-node@v1
      with:
        node-version: 14.x
    - name: Test
      run: |
        yarn install
        yarn build
        yarn test
